# Welcome to my first jupyter notebook

In [1]:
listss = [lambda a=x : x*x for x in range(10)]
print(listss[3])

<function <listcomp>.<lambda> at 0x10eb86d30>


In [3]:
import numpy as np

three_d_array = np.ones([2, 3, 4])

print(three_d_array)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [57]:
arange_array = np.arange(20)
print(arange_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## 1. In Built
### Common Funtions and keywords
interable objects are
- list
- tuple
- dictionary
- set

mutable objects
- list
- dict
- set

In [49]:
# abs: used to return the absolute value of a number,
print('abs function:')
print(abs(10 + 20 - 1000)) # 970

# all: returns True if all items in an iterable (list, tuple, dict, set) are true, otherwise it returns False.
# For dictionaries the all() function checks the keys, not the values.
print('\nall function:')
print(all([10, "vinay", True])) # True
print(all([0, '', None])) # list > False
print(all((0, '', None))) # Tuple > False
print(all({0, '', None})) # Set > False
mydict = {'key' : "Apple", 1 : "Orange"}
print(all(mydict)) # dict > True

# any: returns True if any item in an iterable (list, tuple, dict, set) are true, otherwise it returns False.
# For dictionaries the any() function checks the keys, not the values.
print('\nany function:')
print(any([10, "vinay", True])) # True
print(any([0, '', None])) # list > False
print(any((0, '', None))) # Tuple > False
print(any({0, '', None})) # Set > False
mydict = {None : "Apple", 1 : "Orange"}
print(any(mydict)) # dict > True

# ascii: returns a readable version of any object (Strings, Tuples, Lists, etc).
# function will replace any non-ascii characters with escape characters
print('\nascii function:')
print(ascii('My name is Ståle')) # å will be replaced with \xe5.

# assert: The assert keyword is used when debugging code.
print('\nassert function:')
assert 20+10 == 30

# bin: returns the binary version of a specified integer.
print('\nbin function:')
print(bin(15))

# chr: function returns the character that represents the specified unicode.
print('\nchr function:')
print(chr(65)) # A
print(chr(90)) # Z
print(chr(97)) # a
print(chr(122)) # z

# del: The del keyword is used to delete objects. In Python everything is an object,
# so the del keyword can also be used to delete variables, lists, or parts of a list etc.
print('\ndel function:')
x = "hello"
x1 = ["apple", "banana", "cherry"]
del x1[0]
print(x1) # ['banana', 'cherry']


# delattr(): function is used to delete an attribute from a class.
# It takes two parameters first is an object of the class and
# second is an attribute which we want to delete.

# dir: function returns all properties and methods of the specified object, without the values.
print('\ndir function:')
obj = list()
print(dir(obj))

# enumerate() function takes a collection (e.g. a tuple) and returns it as an enumerate object.
# enumerate() function adds a counter as the key of the enumerate object.
print('\nenumerate function:')
x = ('apple', 'banana', 'cherry')
y = enumerate(x)
print(list(y)) # [(0, 'apple'), (1, 'banana'), (2, 'cherry')]

# eval() function evaluates the specified expression,
# if the expression is a legal Python statement, it will be executed.
print('\neval function:')
x = 'print(55)'
eval(x)

# exec() function executes the specified Python code.
# function accepts large blocks of code, unlike the eval() function which only accepts a single expression
print('\nexec function:')
x = 'name = "John"\nprint(name)'
exec(x)

# format() method formats the specified value(s) and insert them inside the string's placeholder.
print('\nformat function:')
x = 'name = "John"\nprint(name)'
exec(x)

# hash() returns the hash value of an immutable object but not for list, dict, set 
print('\nformat function:')
obj1 = {'key1': "vinay"}
obj2 = {'key1': "vinay"}
print(id(obj1), id(obj2)) # ids are different
print(hash(str(obj1)), hash(str(obj2))) # generate same hash

# isinstance: function returns True if the specified object is of the specified type, otherwise False.
print('\nisinstance function:')
obj3 = {}
print(isinstance(obj3, dict))

# iter(): method returns the iterator object, it is used to convert an iterable to the iterator.
# next() function returns the next item in an iterator.
print('\niter function:')
# initializing list
lis1 = [1, 2, 3, 4, 5]
# printing type
print("The list is of type : " + str(type(lis1))) 
# converting list using iter()
lis1 = iter(lis1)
# printing type
print("The iterator is of type : " + str(type(lis1)))
# using next() to print iterator values
print(next(lis1))
print(next(lis1))
print(next(lis1))
print(next(lis1))
print(next(lis1))

# pass: The pass statement is a null statement.
def todoFunction():
    pass

abs function:
970

all function:
True
False
False
False
True

any function:
True
False
False
False
True

ascii function:
'My name is St\xe5le'

assert function:

bin function:
0b1111

chr function:
A
Z
a
z

del function:
['banana', 'cherry']

dir function:
['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']

enumerate function:
[(0, 'apple'), (1, 'banana'), (2, 'cherry')]

eval function:
55

exec function:
John

format function:
John

format function:
140467716550

### Serialization and deserialization in python

In [31]:
import json

obj1 = {'key1': "vinay"}
print(json.loads(json.dumps(obj1)))

{'key1': 'vinay'}


### float to integer conversion

In [58]:
import math

i1 = 10.50

print(int(i1)) # omit decimal part
print(round(i1)) # nearest integer
print(math.floor(i1)) # lower interger
print(math.ceil(i1)) # upper interger

10
10
10
11


### Set and their functions

In [66]:
set1 = set() # way1
set2 = set((1, 3, 5)) #way2 using tuple
set3 = set([1, 3, 5]) #way3 using list
set4 = set({'k1': '11', 'k2': '45'}) #way4 using dict. set of keys
print(set1)
print(set2)
print(set3)
print(set4)

set()
{1, 3, 5}
{1, 3, 5}
{'k2', 'k1'}


### String and their functions

In [113]:
str1 = "myself Vinay singh"

print(str1.capitalize()) # first char in upper case
print(str1.casefold()) # all the characters are lower case
print(str1.count("V")) # count the string
print(str1.find("not")) # find and return index no or return -1
# print(str1.index("not")) # find and return index no or throws exception
print(str1.isalpha()) # check if all chars are alphabet. chrs are not alphabet: (space)!#%&? etc.
print(str1.isalnum()) # check if all chars are alphabet and int. chrs are not alphanumeric: (space)!#%&? etc.
print(str1.isdecimal())
print(str1.isdigit())
print(str1.isidentifier())
print(str1.islower())
print(str1.isnumeric())
print(str1.isprintable())
print(str1.isspace())
print(str1.istitle()) # check if first char is in upper case
print(str1.isprintable())
print(str1.isupper())
print("".join([])) # join all items using string
print(str1.lower())
print(str1.lstrip()) # remove leading spaces or chars whatever passed
str1_trans_table = str1.maketrans("Vinay", "vinay")
print(str1.translate(str1_trans_table)) # replace chars
print(str1.partition(" ")) # return tuple containing three items. first part, separator, last part
print(str1.replace(" ", "_"))
print(str1.title()) # capitalize start char in each word
print(str1.split(' '))
print(str1.rsplit(" "))

Myself vinay singh
myself vinay singh
1
-1
False
False
False
False
False
False
False
True
False
False
True
False

myself vinay singh
myself Vinay singh
myself vinay singh
('myself', ' ', 'Vinay singh')
myself_Vinay_singh
Myself Vinay Singh
['myself', 'Vinay', 'singh']
['myself', 'Vinay', 'singh']


### List helper functions

In [33]:
list_numbers = [i for i in range(20)] # way1
list_numbers1 = list([1, "vinay", 5, 6, "singh"]) # way2
list_numbers2 = list((1, "vinay", 5, 6, "singh")) # way3
list_strings = [''.join([chr(j) for j in range(65, i)]) for i in range(70, 80)] #way4

#append
list_numbers1.append("name")
print("appned: ", list_numbers1)

#insert
list_numbers1.insert(1, "I am 2nd placed")
print("insert:", list_numbers1)

#extend
list_numbers1.extend(list_numbers2)
print("extend_list:", list_numbers1)

#pop
list_numbers1.pop()
print("pop:", list_numbers1)

#remove
list_numbers1.remove(6)
print("remove:", list_numbers1)

#clear
list_numbers1.clear()
print("clear:", list_numbers1)

#sort
list_strings.sort()
print("sort:", list_strings)

#index
idx = list_numbers2.index("vinay")
print("index:", idx)

#count
print(list_numbers2.count("vinay"))

#reverse
list_numbers2.reverse()
print("reverse: ", list_numbers2)

#copy
copy_list = list_numbers2.copy()
copy_list.append(8990)
print("copy: ", list_numbers2)

#slice the array


appned:  [1, 'vinay', 5, 6, 'singh', 'name']
extend_list: [1, 'vinay', 5, 6, 'singh', 'name', 1, 'vinay', 5, 6, 'singh']
insert: [1, 'I am 2nd placed', 'vinay', 5, 6, 'singh', 'name', 1, 'vinay', 5, 6, 'singh']
pop: [1, 'I am 2nd placed', 'vinay', 5, 6, 'singh', 'name', 1, 'vinay', 5, 6]
remove: [1, 'I am 2nd placed', 'vinay', 5, 'singh', 'name', 1, 'vinay', 5, 6]
clear: []
sort: ['ABCDE', 'ABCDEF', 'ABCDEFG', 'ABCDEFGH', 'ABCDEFGHI', 'ABCDEFGHIJ', 'ABCDEFGHIJK', 'ABCDEFGHIJKL', 'ABCDEFGHIJKLM', 'ABCDEFGHIJKLMN']
index: 1
1
reverse:  ['singh', 6, 5, 'vinay', 1]
copy:  ['singh', 6, 5, 'vinay', 1]


### Dictionary and helper functions

In [141]:
dict1 = {'key1': "value"} # way1
dict2 = dict() #way2
dict3 = dict({'key1': "val", 'key_to_delete': 'key_to_delete_value', None: 'vinay'}) #way3

print(dict3.items()) # dict_items([('key1', 'val')]). list of tuple containing key and value
print(dict3.values()) # list of values
print(dict3.keys()) # list of keys
print(dict3['key1']) # access value of a key. throws exception if no key in dict
print(dict3.get('wrong_key')) # return None if there is no key
print(dict3.pop('key_to_delete')) # delete key-value pair if exist and return value or throws error
print(dict1.popitem()) # The popitem() method removes the item that was last inserted into the dictionary
dict1['new_key'] = "new value"
print(dict1)
dict1.clear()
print(dict1)
print(dict1.setdefault("key3", "key3value")) # return the value of key if exist or add the key-value pair
print(dict1.setdefault("key3", "key3valuenew"))
car = {"brand": "Ford","model": "Mustang"}
car.update({"color": "White", "year": 1964}) # extends the dictionary
print(car) # {'brand': 'Ford', 'model': 'Mustang', 'color': 'White', 'year': 1964}

#copy: fun creates shallow copy of the dict
car1 = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964,
  'd1': {
      'd1k1': 10
  }
}
car1_copy = car1.copy()
car1_copy['d1']['d1k1'] = 20
print(car1_copy)
print(car1)

# fromkeys() method returns a dictionary with the specified keys and the specified value.
keys_tuple = ('key1', 'key2', 'key3')
keys_value = 0
thisdict = dict.fromkeys(keys_tuple, keys_value)
print(thisdict) # {'key1': 0, 'key2': 0, 'key3': 0}

dict_items([('key1', 'val'), ('key_to_delete', 'key_to_delete_value'), (None, 'vinay')])
dict_values(['val', 'key_to_delete_value', 'vinay'])
dict_keys(['key1', 'key_to_delete', None])
val
None
key_to_delete_value
('key1', 'value')
{'new_key': 'new value'}
{}
key3value
key3value
{'brand': 'Ford', 'model': 'Mustang', 'color': 'White', 'year': 1964}
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'd1': {'d1k1': 20}}
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'd1': {'d1k1': 20}}
{'key1': 0, 'key2': 0, 'key3': 0}


## 2. Packages and Modules
### numpy and its functions

In [2]:
import numpy as np

# way1
np_array = np.array([100, 101, 103, 104]) # 1 Dim

# way2. Both ways are same and create multi-dimensioanl arrays. 2 Dim
np_array2 = np.array([[205, 201, 203, 204], [205, 201, 203, 204], [205, 201, 203, 204], [205, 201, 203, 204]])

print('Numpy array type', type(np_array2))
print('Numpy array dim', np_array2.ndim)

Numpy array type <class 'numpy.ndarray'>
Numpy array dim 2


In [9]:
zeros_array_1d = np.zeros(5, dtype=int)
zeros_array_2d = np.zeros((5,2), dtype=int)
print('zeros 2d array', zeros_array_2d)

zeros 2d array [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [10]:
ones_array_1d = np.ones(5, dtype=int)
ones_array_2d = np.ones((5,2), dtype=int)
print('ones 2d array', ones_array_2d)

ones 2d array [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [3]:
np.empty((2,3))

array([[ 1.28822975e-231, -3.11108127e+231,  1.48219694e-323],
       [ 0.00000000e+000,  0.00000000e+000,  4.17201348e-309]])

In [6]:
# Create numpy arrays
# np.empty((2,3))
np.eye(3)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### pandas and its functions

In [4]:
import pandas as pd

df1 = pd.DataFrame(data=np.zeros((3,3)), columns=['col1', 'col2', 'col3'], index=['row1', 'row2', 'row3'])
print('\nFirst dataframe:\n', df1)

df2 = df1.apply(lambda x: x + np.random.randint(100))
print('\nSecond dataframe:\n', df2)

df3 = df1.append(df2)
print('\nThird dataframe:\n', df3)


First dataframe:
       col1  col2  col3
row1   0.0   0.0   0.0
row2   0.0   0.0   0.0
row3   0.0   0.0   0.0

Second dataframe:
       col1  col2  col3
row1  42.0  36.0  46.0
row2  42.0  36.0  46.0
row3  42.0  36.0  46.0

Third dataframe:
       col1  col2  col3
row1   0.0   0.0   0.0
row2   0.0   0.0   0.0
row3   0.0   0.0   0.0
row1  42.0  36.0  46.0
row2  42.0  36.0  46.0
row3  42.0  36.0  46.0


In [19]:
# Pandas indexing: loc. Loc first take rows and then col.
# valid syntax is loc[row, col]
# valid syntax is loc[list_of_rows, list_of_cols]
val_row1_col1 = df3.loc[['row1'], ['col1']]
print('\nValue of row1 and col1:\n', val_row1_col1)


Value of row1 and col1:
       col1
row1   0.0
row1  42.0

Value of 3rd row and 5th row:
 col1    0.0
col2    0.0
col3    0.0
Name: row1, dtype: float64


In [26]:
# Pandas indexing: iloc
# valid syntax is loc[row_index, col_index]
# valid syntax is loc[list_of_rows_index, list_of_cols_index]
val_3rdrow_5throw = df3.iloc[[0,2],[1]]
print('\nValue of 0th row and 2nd row with col2:\n', val_3rdrow_5throw)


Value of 0th row and 2nd row with col2:
       col2
row1   0.0
row3   0.0


In [28]:
data = {'emp_ID': ['1011', '1012', '1013', '1014', '1015'],

                    'employee_name': ['Alex', 'John', 'Zender', 'Alex', 'Walter'],

                     'salary': ['273805', '272700', '349700', '734744', '374333']}

df = pd.DataFrame(data, index=['one','two','three','four','five'])
df

emp_ID employee_name  salary
one     1011          Alex  273805
two     1012          John  272700
three   1013        Zender  349700
four    1014          Alex  734744
five    1015        Walter  374333

In [31]:
# access Alex
df.iloc[0,1]

'Alex'

In [34]:
df = pd.DataFrame({'number': [101, 290, 389, 478, 567]})
df

number
0     101
1     290
2     389
3     478
4     567

In [35]:
df["number"].apply(lambda x: x + 1)

0    102
1    291
2    390
3    479
4    568
Name: number, dtype: int64