# Agenda
- Numpy
  - Arrays
  - Arrays Vs Lists
  - Array indexing and slicing
  - Array operations and functions
- Pandas
  - Series
    - Creation
    - Indexing
    - Functions
  - Dataframe
    - Creation
    - Indexing
    - Functions

# 1. Numpy
- It is the fundamental package for scientific computing with Python
- It provides a high-performance multidimensional array object, and tools for working with these arrays
- It has important features as :
  - A powerful N-dimensional array object
  - Sophisticated (broadcasting) functions
  - Useful linear algebra, Fourier transform, and random number capabilities
- Arbitrary data-types can be defined using Numpy which allows NumPy to seamlessly and speedily integrate with a wide variety of databases
- NumPy is used to work with arrays. The array object in NumPy is called ndarray

## Why do we need Numpy Arrays
- With numpy arrays, mathematical operations are executed more efficiently and with less code compared to Python’s built-in data structures. 
- Hence, numpy arrays are very useful when working with a lasrge data.

## Advantages over Python lists
- Fast computation
- Consumes less memory

## Differences between Numpy Array and Lists
 - Arrays are homogeneous whereas Lists can be homogeneous or heterogeneous
 - Element wise operation is possible in arrays but not possible in lists
 - Arrays are very useful for multi-dimensional data. 

## 1.1 Numpy array creation

NumPy arrays are the one of the most widely used data structuring techniques by Data Scientists. 

Numpy arrays are of two types: Vectors and Matrices. 

Vectors are 1-dimensional arrays and matrices are 2-dimensional arrays(A Matrix can still possess a single row or a column).

We shall begin our learning with how to create NumPy Arrays.
- Numpy arrays can be created using different functions :
  - array()
  - arange()
  - linspace()
  - empty()
  - eye(), ones(), zeros(), identity() and many more

### np.array()
- We can create a NumPy ndarray object by using the array() function
- 0-D array - or Scalars, are the elements in an array. Each value in an array is a 0-D array
- 1-D array - An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array
- 2-D array - An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix
- 3-D - An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor

In [ ]:
import numpy as np

# 0-D array
new_array = np.array(40)
print(f" \nArray : {new_array} ")
print(f" Type of array : {type(new_array)} ")
print(f" Array dimension : {new_array.ndim}") # array dimension can be checked using ndim

#1-D array
new_array = np.array([20,40,60,80])
print(f" \nArray : {new_array} ")
print(f" Type of array : {type(new_array)} ")
print(f" Array dimension : {new_array.ndim}")

#2-D array
new_array = np.array([[20,40], [60,80]])
print(f" \nArray : {new_array} ")
print(f" Type of array : {type(new_array)} ")
print(f" Array dimension : {new_array.ndim}")  

#3-D array
new_array = np.array([[[20,40] ,[60,80]]])
print(f" \nArray : {new_array} ")
print(f" Type of array : {type(new_array)} ")
print(f" Array dimension : {new_array.ndim}")

 
Array : 40 
 Type of array : <class 'numpy.ndarray'> 
 Array dimension : 0
 
Array : [20 40 60 80] 
 Type of array : <class 'numpy.ndarray'> 
 Array dimension : 1
 
Array : [[20 40]
 [60 80]] 
 Type of array : <class 'numpy.ndarray'> 
 Array dimension : 2
 
Array : [[[20 40]
  [60 80]]] 
 Type of array : <class 'numpy.ndarray'> 
 Array dimension : 3


### np.arange()
- The arange() function is one of the Numpy's most used method for creating an array within a specified range
- Syntax : np.arange(start, end, step, dtype)

In [ ]:
# creating an array starting from 0 ending with 10 
# and increasing with a step of 2
arange_array = np.arange(0,11,2)   # writing 11 instead of 10 since range is exclusive
print(f"First array : {arange_array}")

# array starting from 50 going till 120 with step of 4

arr = np.arange(50,121,4)
print(f"Second Array : {arr}")

First array : [ 0  2  4  6  8 10]
Second Array : [ 50  54  58  62  66  70  74  78  82  86  90  94  98 102 106 110 114 118]


### np.linspace()
- Like arange() function, linspace() function can also be used to create Numpy array but with more discipline
- Syntax : linspace(start_index, end_index, num_of_elements)
- linspace() function takes arguments: start index, end index and the number of elements to be outputted. These number of elements would be linearly spaced in the range mentioned

In [ ]:
# range 15, 75 spaced appropriately.
arr = np.linspace(15, 75, 10)     
print(f"First Array : {arr}")

# properly spaced array of 25 elements
arr1 = np.linspace(50,100,25)   
print(f"Second Array : {arr1}")

First Array : [15.         21.66666667 28.33333333 35.         41.66666667 48.33333333
 55.         61.66666667 68.33333333 75.        ]
Second Array : [ 50.          52.08333333  54.16666667  56.25        58.33333333
  60.41666667  62.5         64.58333333  66.66666667  68.75
  70.83333333  72.91666667  75.          77.08333333  79.16666667
  81.25        83.33333333  85.41666667  87.5         89.58333333
  91.66666667  93.75        95.83333333  97.91666667 100.        ]


## 1.2 Numpy indexing and slicing
- Contents of ndarray object can be accessed and modified by indexing or slicing, just like Python's in-built container objects
  - Field access
  - Basic slicing
  - Advance indexing
    - Integer indexing
    - Boolean indexing

### Field access
- Field access in python means taking elements from one given index to another given index
- If we don't pass start its considered 0
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered 1

In [ ]:
new_array = np.array([1,10,20,2,30,3,40,4,50,5])  # 1-D array created
new_array[-3:3:-1]                              #(start,end,step)

array([ 4, 40,  3, 30])

In [ ]:
new_array = np.array([[[1],[2],[3]], [[4],[5],[6]]])
new_array.shape  # creating a 3-D array

(2, 3, 1)

In [ ]:
new_array[1:2]

array([[[4],
        [5],
        [6]]])

### Slicing
- Syntax - slice(start, end, step)

In [ ]:
new_array = np.arange(8)
new_array[slice(1,6,2)]

array([1, 3, 5])

### Advance indexing - integer
- This mechanism helps in selecting any arbitrary item in an array based on its Ndimensional index
- Each integer array represents the number of indexes into that dimension

In [ ]:
new_array = np.array([[10, 2], [6, 4], [5, 1]]) 
integer_indexing = new_array[[0,1,2], [0,1,0]] # row index represents row numbers, column index represents elements to be chosen
integer_indexing

array([10,  4,  5])

### Advance indexing - boolean
- This type of advanced indexing is used when the resultant object is meant to be the result of Boolean operations, such as comparison operators

In [ ]:
new_array[new_array > 5]

array([10,  6])

## 1.3 Numpy Operations/Functions
- Array manipulation functions
- Binary functions
- String functions
- Arithmetic functions
- Statistical functions

### 1.3.1 Array manipulation functions
- The Array manipulation functions of NumPy module helps us to perform changes in the array elements
- reshape()
- concatenate()
- sort()


#### reshape() function

In [ ]:
arr1 = np.arange(4)
print(f'Elements of an array1:\n : {arr1}')
 
arr2 = np.arange(4,8)
print(f'Elements of an array2:\n : {arr2}')
 
res1 = arr1.reshape(2,2)
print(f'Reshaped array with 2x2 dimensions:\n : {res1}')
 
res2 = arr2.reshape(2,2)
print(f'Reshaped array with 2x2 dimensions:\n : {res2}')

Elements of an array1:
 : [0 1 2 3]
Elements of an array2:
 : [4 5 6 7]
Reshaped array with 2x2 dimensions:
 : [[0 1]
 [2 3]]
Reshaped array with 2x2 dimensions:
 : [[4 5]
 [6 7]]


#### concatenate() function

In [ ]:
print("Concatenation two arrays:\n")
concat = np.concatenate((arr1,arr2))
print(concat)

Concatenation two arrays:

[0 1 2 3 4 5 6 7]


#### sort() function

In [ ]:
number_array = np.array([20,4,10,8])
print(f"Before sorting : {number_array} ")
sorted_array = np.sort(number_array, kind='quick sort')
print(f"After sorting : {sorted_array} ")

Before sorting : [20  4 10  8] 
After sorting : [ 4  8 10 20] 


### 1.3.2 Arithmetic functions
- numpy.add()
- numpy.subtract()
- numpy.multiply()
- numpy.divide()
- numpy.mod()
- numpy.power()

In [ ]:
x = np.arange(4) 
print(f"Elements of array 'x': {x}")
 
y = np.arange(4,8) 
print(f"Elements of array 'y': {y}")
 
add = np.add(x,y)
print(f"Addition of x and y: {add}")
 
subtract = np.subtract(x,y)
print(f"Subtraction of x and y: {subtract}")
 
mul = np.multiply(x,y)
print(f"Multiplication of x and y: {mul}")
 
div = np.divide(x,y)
print(f"Division of x and y: {div}")
 
mod = np.mod(x,y)
print(f"Remainder array of x and y: {mod}")
 
pwr = np.power(x,y)
print("Power value of x^y:\n",pwr)


Elements of array 'x': [0 1 2 3]
Elements of array 'y': [4 5 6 7]
Addition of x and y: [ 4  6  8 10]
Subtraction of x and y: [-4 -4 -4 -4]
Multiplication of x and y: [ 0  5 12 21]
Division of x and y: [0.         0.2        0.33333333 0.42857143]
Remainder array of x and y: [0 1 2 3]
Power value of x^y:
 [   0    1   64 2187]


### 1.3.3 String functions
- With NumPy String functions, we can manipulate the string values contained in an array
- numpy.char.add()
- numpy.char.capitalize()
- numpy.char.lower()
- numpy.char.upper()
- numpy.char.replace()

In [ ]:
res =  np.char.add(['Python'],[' JournalDev'])
 
print(f"Concatenating two strings:\n : {res}")

Concatenating two strings:
 : ['Python JournalDev']


In [ ]:
print(f"Capitalizing the string : {np.char.capitalize('python data')}")

Capitalizing the string : Python data


In [ ]:
print(f"Converting to lower case : {np.char.lower('PYTHON')}")

Converting to lower case : python


In [ ]:
print(f"Converting to UPPER case : {np.char.upper('python')}")

Converting to UPPER case : PYTHON


In [ ]:
print(f"Replacing string within a string : {np.char.replace ('Python Tutorials with GL', 'GL', 'GreatLearning')}")

Replacing string within a string : Python Tutorials with GreatLearning


### 1.3.4 Binary functions
- numpy.bitwise_and()
- numpy.bitwise_or()
- numpy.bitwise_xor()
- numpy.invert()
- numpy.left_shift()
- numpy.right_shift()

#### numpy.bitwise_and()

In [ ]:
import numpy as np
in_num1 = 10
in_num2 = 11
 
print (f"Input  number1 : {in_num1}")
print (f"Input  number2 : {in_num2}") 
   
out_num = np.bitwise_and(in_num1, in_num2) 
print (f"bitwise_and of 10 and 11 : {out_num}") 

Input  number1 : 10
Input  number2 : 11
bitwise_and of 10 and 11 : 10


#### numpy.bitwise_or()

In [ ]:
out_num = np.bitwise_or(in_num1, in_num2) 
print (f"bitwise_or of 10 and 11 : {out_num}")

bitwise_or of 10 and 11 : 11


### 1.3.5 Statistical functions
- NumPy Statistical functions are very helpful in the domain of data mining and analysis of the huge amount of traits in the data
- numpy.median()
- numpy.mean()
- numpy.average()
- numpy.std()

In [ ]:
x = np.array([10,20,30,4,50,60]) 
 
med = np.median(x)
print(f"Median value of array: {med}")
 
mean = np.mean(x)
print(f"Mean value of array: {mean}")
 
avg = np.average(x)
print(f"Average value of array: {avg}")
 
std = np.std(x)
print(f"Standard deviation value of array: {std}")

Median value of array: 25.0
Mean value of array: 29.0
Average value of array: 29.0
Standard deviation value of array: 20.2895703913776


## 1.4 Numpy Selection techniques
- numpy.select()
- numpy.where()
- numpy.choose()
- numpy.random.choice()

### numpy.select()
- Return an array drawn from elements in choicelist, depending on conditions
- Syntax : numpy.select(condlist, choicelist, default=0)

In [ ]:
# create an array
arr = np.arange(20)

In [ ]:
np.select(condlist= [arr<5, arr>7], choicelist= [arr, arr**2])

array([  0,   1,   2,   3,   4,   0,   0,   0,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

### numpy.where()
- Return elements chosen from x or y depending on condition
- Syntax : numpy.where(condition[, x, y])

In [ ]:
np.where(arr < 6, arr, 2*arr)

array([ 0,  1,  2,  3,  4,  5, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

### numpy.choose()
- Construct an array from an index array and a list of arrays to choose from
- Syntax : numpy.choose(a, choices, out=None, mode='raise')

In [ ]:
choices = [[0, 1, 10, 9], [10, 20, 30, 40],
  [50, 51, 52, 53], [60, 61, 62, 63]]
np.choose([2,3,1,0], choices)

array([50, 61, 30,  9])

### numpy.random.choice()
- Generates a random sample from a given 1-D array
- Syntax : random.choice(a, size=None, replace=True, p=None)

In [ ]:
np.random.choice(20,4)

array([16,  4, 12,  0])